(function(){
'use strict';
const V=window.RahbarV2;if(!V)return;
let pending=null;
let filters={agent:'all',debt:'all',status:'all',sort:'newest'};
function e(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function money(v){return Number(v||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}
function api(a,b){return V.request(a,b)}
function cs(){return V.clients()||[]}
function cAt(i){return cs()[Number(i)]}
function note(t){return '<div class="v2-note">'+e(t)+'</div>'}
function sheet(title,body){sh.innerHTML='<div style="width:44px;height:5px;border-radius:5px;background:var(--line);margin:0 auto 14px"></div><div class="v2-title-row"><h3>'+e(title)+'</h3><button class="v2-x" onclick="closeS()">×</button></div>'+body;sh.classList.add('on');ov.classList.add('on');if(tg&&tg.BackButton)tg.BackButton.show()}
function bytes(v){const r=atob(v),o=new Uint8Array(r.length);for(let i=0;i<r.length;i++)o[i]=r.charCodeAt(i);return o}
function dl(f,name){const b=new Blob([bytes(f.base64)],{type:f.mime||'application/octet-stream'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=f.filename||name;a.target='_blank';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(u)},60000)}
if(!document.getElementById('v2-legacy-style')){const st=document.createElement('style');st.id='v2-legacy-style';st.textContent=['.v2-title-row{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:12px}', '.v2-title-row h3{margin:0;font-size:18px}', '.v2-x{width:34px;height:34px;border:0;border-radius:12px;background:var(--soft);color:var(--tx);font-size:23px}', '.v2-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}', '.v2-actions.three{grid-template-columns:repeat(3,1fr)}', '.v2-btn{border:0;border-radius:12px;padding:10px 9px;background:var(--soft);color:var(--pri);font-weight:800;font-size:11px}', '.v2-btn.primary{background:var(--pri);color:#fff}', '.v2-btn.danger{background:#feecef;color:#d92d47}', '.v2-note{padding:10px 11px;border-radius:12px;background:var(--soft);color:var(--mu);font-size:11px;line-height:1.5;margin:8px 0}', '.v2-form{display:grid;gap:10px}', '.v2-form label{font-size:11px;color:var(--mu);font-weight:700}', '.v2-form input,.v2-form textarea,.v2-form select{width:100%;box-sizing:border-box;margin-top:5px;border:1px solid var(--line);background:var(--bg);color:var(--tx);border-radius:12px;padding:10px;font:inherit}', '.v2-form textarea{min-height:72px;resize:vertical}', '.v2-list{display:grid;gap:7px}', '.v2-item{border:1px solid var(--line);border-radius:13px;padding:10px;background:var(--soft)}', '.v2-item b{font-size:12px}', '.v2-item small{display:block;color:var(--mu);font-size:10px;margin-top:3px}', '.v2-toolbar{display:flex;gap:7px;overflow-x:auto;scrollbar-width:none;margin:8px 0 12px}', '.v2-toolbar button{flex:none;border:0;background:var(--soft);color:var(--pri);border-radius:18px;padding:8px 10px;font-size:10px;font-weight:800}', '.v2-filter select{width:100%;border:0;outline:0;background:transparent;color:var(--tx);font-size:12px;font-weight:700;margin-top:2px}'].join('\n');document.head.appendChild(st)}
function toolbar(){const sec=document.querySelectorAll('section')[2],sum=sec&&sec.querySelector('#clsum');if(!sum||sec.querySelector('#v2-client-toolbar'))return;const b=document.createElement('div');b.id='v2-client-toolbar';b.className='v2-toolbar';b.innerHTML='<button onclick="RahbarLegacyClients.exportAll(\'pdf\')">📄 Barcha PDF</button><button onclick="RahbarLegacyClients.exportAll(\'xlsx\')">📊 Barcha Excel</button><button onclick="RahbarLegacyClients.clearFilters()">↺ Filtr</button>';sum.after(b)}
function installFilters(){const sec=document.querySelectorAll('section')[2],fl=sec&&sec.querySelector('.fl');if(!fl)return;const opts=(V.agents()||[]).map(function(a){return '<option value="'+a.id+'">'+e(a.name)+'</option>'}).join('');fl.innerHTML='<div class="v2-filter"><small>Agent</small><select id="v2-fa"><option value="all">Barchasi</option>'+opts+'</select></div><div class="v2-filter"><small>Qarz</small><select id="v2-fd"><option value="all">Barchasi</option><option value="debt">Qarzdor</option><option value="clear">Qarzsiz</option></select></div><div class="v2-filter"><small>Holat</small><select id="v2-fs"><option value="all">Barchasi</option><option value="active">Faol</option><option value="interested">Qiziqqan</option><option value="refused">Rad etgan</option><option value="waiting">Kutmoqda</option></select></div><div class="v2-filter"><small>Saralash</small><select id="v2-fo"><option value="newest">So‘nggi faollik</option><option value="debt">Qarz bo‘yicha</option><option value="name">Nom bo‘yicha</option><option value="oldest">Eski faollik</option></select></div>';[['v2-fa','agent'],['v2-fd','debt'],['v2-fs','status'],['v2-fo','sort']].forEach(function(x){const el=document.getElementById(x[0]);el.value=filters[x[1]];el.onchange=function(){filters[x[1]]=el.value;rc()}});toolbar()}
rc=function(){const meta=cs(),q=String(qq||'').trim().toLowerCase();let ids=CL.map(function(_,i){return i}).filter(function(i){const c=CL[i],m=meta[i]||{};if(cf&&c[4]!==cf)return false;if(q&&String([c[0],c[1],c[2],m.person,m.phone,m.note].join(' ')).toLowerCase().indexOf(q)<0)return false;if(filters.agent!=='all'&&String(m.agentId)!==String(filters.agent))return false;if(filters.debt==='debt'&&Number(m.debtUsd||0)<=0)return false;if(filters.debt==='clear'&&Number(m.debtUsd||0)>0)return false;if(filters.status!=='all'&&String(m.status)!==filters.status)return false;return true});ids.sort(function(a,b){const A=meta[a]||{},B=meta[b]||{};if(filters.sort==='debt')return Number(B.debtUsd||0)-Number(A.debtUsd||0);if(filters.sort==='name')return String(A.name||'').localeCompare(String(B.name||''),'uz');if(filters.sort==='oldest')return Number(A.lastTs||A.createdTs||0)-Number(B.lastTs||B.createdTs||0);return Number(B.lastTs||B.createdTs||0)-Number(A.lastTs||A.createdTs||0)});const rows=ids.map(function(i){return CL[i]});cllist.innerHTML=rows.map(clRow).join('')||'<div class="c" style="text-align:center;color:var(--mu)">Hech narsa topilmadi</div>';const sum=ids.reduce(function(s,i){return s+Number((meta[i]||{}).debtUsd||0)},0);clsum.innerHTML='<div class="kp"><div class="ic" style="--a:#1f6bff">👛</div><div style="flex:1"><small>Tanlangan bo‘yicha jami qarz</small><b>'+money(sum)+' $ <em style="font-size:12px;color:var(--mu);font-weight:600">· '+ids.length+' mijoz</em></b></div></div>'}
const baseOpen=openC;
openC=async function(i){await baseOpen(i);const c=cAt(i);if(!c)return;const old=sh.querySelector('#v2-client-actions');if(old)old.remove();const d=document.createElement('div');d.id='v2-client-actions';d.innerHTML='<div class="v2-actions three"><button class="v2-btn primary" onclick="RahbarLegacyClients.edit('+i+')">✏️ Tahrirlash</button><button class="v2-btn" onclick="RahbarLegacyClients.exportOne('+i+',\'pdf\')">📄 PDF</button><button class="v2-btn" onclick="RahbarLegacyClients.exportOne('+i+',\'xlsx\')">📊 Excel</button><button class="v2-btn" onclick="RahbarLegacyClients.navigate('+i+')">🧭 Yo‘l</button><button class="v2-btn danger" onclick="RahbarLegacyClients.remove('+i+')">🗑 O‘chirish</button><button class="v2-btn" onclick="closeS()">Yopish</button></div>';sh.appendChild(d)}
async function edit(i){const c=cAt(i);if(!c)return;try{const d=await api('client_detail',{clientId:c.id});sheet('Mijozni tahrirlash','<div class="v2-form"><label>Kontakt shaxs<input id="v2-cn" value="'+e(d.person||'')+'"></label><label>Do‘kon nomi<input id="v2-cs" value="'+e(d.shopName||'')+'"></label><label>Telefon<input id="v2-cp" value="'+e(d.phone||'')+'"></label><label>Manzil<textarea id="v2-ca">'+e(d.address||'')+'</textarea></label><label>To‘lov sanasi<input id="v2-cd" value="'+e(d.paymentDue||'')+'"></label><label>Izoh<textarea id="v2-cc">'+e(d.comment||'')+'</textarea></label>'+note('Tovar, qarz va to‘lov tarixi bu oynadan o‘zgartirilmaydi. O‘zgarish auditda saqlanadi.')+'<button class="v2-btn primary" onclick="RahbarLegacyClients.preview('+i+')">Tekshirish</button><button class="v2-btn danger" onclick="RahbarLegacyClients.remove('+i+')">🗑 O‘chirish</button></div>')}catch(x){toast(x.message||'Mijoz ochilmadi')}}
async function preview(i){const c=cAt(i);if(!c)return;const values={name:document.getElementById('v2-cn').value,shop_name:document.getElementById('v2-cs').value,phone:document.getElementById('v2-cp').value,address:document.getElementById('v2-ca').value,payment_due:document.getElementById('v2-cd').value,comment:document.getElementById('v2-cc').value};try{pending=await api('client_edit_preview',{clientId:c.id,values:values});sheet('O‘zgarishni tasdiqlash',note('Quyidagi o‘zgarishlar saqlanadi.')+'<div class="v2-list">'+pending.changes.map(function(x){return '<div class="v2-item"><b>'+e(x.field)+'</b><small>'+e(x.old||'—')+' → '+e(x.new||'—')+'</small></div>'}).join('')+'</div><div class="v2-actions"><button class="v2-btn primary" onclick="RahbarLegacyClients.commit()">✅ Saqlash</button><button class="v2-btn" onclick="RahbarLegacyClients.edit('+i+')">← Qaytish</button></div>')}catch(x){toast(x.message||'Tekshirib bo‘lmadi')}}
async function commit(){if(!pending)return;const p=pending;pending=null;try{await api('client_edit_commit',{clientId:p.clientId,values:p.values,confirm:true});closeS();await V.reload();installFilters();toast('✅ Mijoz saqlandi')}catch(x){toast(x.message||'Saqlanmadi')}}
async function remove(i){const c=cAt(i);if(!c)return;try{const p=await api('client_delete_preview',{clientId:c.id});if(!confirm('Mijozni aktiv ro‘yxatdan o‘chirasizmi?\n\n'+p.name+'\nQarz: '+money(p.debtUsd)+' USD\n'+p.eventCount+' operatsiya · '+p.visitCount+' tashrif\n\n'+p.warning))return;if(!confirm('OXIRGI TASDIQ\n\n'+p.name+' mijozini o‘chirishni tasdiqlaysizmi?'))return;await api('client_delete_commit',{clientId:c.id,confirm:true});closeS();await V.reload();installFilters();toast('Mijoz o‘chirildi · tarix arxivda saqlandi')}catch(x){toast(x.message||'O‘chirilmadi')}}
async function exportOne(i,format){const c=cAt(i);if(!c)return;toast((format==='pdf'?'PDF':'Excel')+' tayyorlanmoqda…');try{const f=await api('client_export',{clientId:c.id,format:format});dl(f,'ASMAN-akt.'+format);toast('Akt sverka tayyor')}catch(x){toast(x.message||'Fayl tayyorlanmadi')}}
async function exportAll(format){toast('Umumiy akt tayyorlanmoqda…');try{const f=await api('all_clients_export',{format:format});dl(f,'ASMAN-barcha-mijozlar.'+format);toast('Umumiy akt tayyor')}catch(x){toast(x.message||'Fayl tayyorlanmadi')}}
function navigate(i){const c=cAt(i);if(!c||!Number.isFinite(Number(c.lat))||!Number.isFinite(Number(c.lon))){toast('GPS koordinata yo‘q');return}const u='https://www.google.com/maps?q='+encodeURIComponent(c.lat+','+c.lon);if(tg&&tg.openLink)tg.openLink(u);else window.open(u,'_blank','noopener')}
function clearFilters(){filters={agent:'all',debt:'all',status:'all',sort:'newest'};installFilters();rc()}
window.RahbarLegacyClients={edit:edit,preview:preview,commit:commit,remove:remove,exportOne:exportOne,exportAll:exportAll,navigate:navigate,clearFilters:clearFilters};
installFilters();toolbar();setTimeout(installFilters,700);window.addEventListener('rahbar-v2-data',function(){installFilters();toolbar();rc()});
})();