(function(){
'use strict';
const V=window.RahbarV2;if(!V)return;
let pending=null,periodMap=null,periodLayer=null;
function e(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function money(v){return Number(v||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}
function when(ts){if(!ts)return '—';try{return new Date(Number(ts)*1000).toLocaleString('uz-UZ',{timeZone:'Asia/Tashkent',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}catch(_){return '—'}}
function api(a,b){return V.request(a,b)}
function as(){return V.agents()||[]}
function aAt(i){return as()[Number(i)]}
function aById(id){return as().find(function(a){return Number(a.id)===Number(id)})}
function note(t){return '<div class="v2-note">'+e(t)+'</div>'}
function sheet(title,body){sh.innerHTML='<div style="width:44px;height:5px;border-radius:5px;background:var(--line);margin:0 auto 14px"></div><div class="v2-title-row"><h3>'+e(title)+'</h3><button class="v2-x" onclick="closeS()">×</button></div>'+body;sh.classList.add('on');ov.classList.add('on');if(tg&&tg.BackButton)tg.BackButton.show()}
if(!document.getElementById('v2-agent-style')){const st=document.createElement('style');st.id='v2-agent-style';st.textContent=['.v2-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}', '.v2-grid.three{grid-template-columns:repeat(3,1fr)}', '.v2-card{border:1px solid var(--line);background:var(--soft);border-radius:15px;padding:11px}', '.v2-card small{display:block;color:var(--mu);font-size:10px}', '.v2-card b{display:block;font-size:16px;margin-top:4px}', '.v2-row{display:flex;align-items:center;gap:10px;padding:10px 0;border-bottom:1px solid var(--line)}', '.v2-row:last-child{border-bottom:0}', '.v2-row .grow{flex:1}', '.v2-row b{display:block;font-size:12px}', '.v2-row small{display:block;color:var(--mu);font-size:10px;margin-top:2px}', '.v2-badge{border-radius:20px;padding:5px 8px;font-size:9px;font-weight:800;background:var(--soft)}', '.v2-switch{border:0;border-radius:16px;padding:6px 9px;font-size:9px;font-weight:800}', '.v2-switch.on{background:#e8fff5;color:#087a54}', '.v2-switch.off{background:#feecef;color:#c52c43}', '#v2-period-map{height:280px;border-radius:16px;overflow:hidden;background:var(--soft);margin:10px 0}'].join('\n');document.head.appendChild(st)}
function enhance(){const sec=document.querySelectorAll('section')[1];if(!sec)return;const card=sec.querySelector('.bd > .c');if(!card||card.querySelector('#v2-agent-tools'))return;const d=document.createElement('div');d.id='v2-agent-tools';d.className='v2-actions three';d.innerHTML='<button class="v2-btn primary" onclick="RahbarLegacyAgents.profile(selAgent)">👤 Profil</button><button class="v2-btn" onclick="RahbarLegacyAgents.period(selAgent,\'week\')">📅 7 kun</button><button class="v2-btn" onclick="RahbarLegacyAgents.manage()">⚙️ Boshqaruv</button>';card.appendChild(d)}
async function profile(i){const a=aAt(i);if(!a)return;sheet('Agent boshqaruvi','<div style="padding:20px;text-align:center;color:var(--mu)">Agent yuklanmoqda…</div>');try{const d=await api('agent_detail',{agentId:a.id});renderProfile(d)}catch(x){sheet('Agent boshqaruvi',note(x.message||'Agent ochilmadi'))}}
function renderProfile(d){const stock=(d.stocks||[]).filter(function(x){return Number(x.qty||0)>0});const feats=(d.features||[]).map(function(f){return '<div class="v2-row"><div class="grow"><b>'+e(f.label||f.key)+'</b><small>'+e(f.key)+'</small></div><button class="v2-switch '+(f.enabled?'on':'off')+'" onclick="RahbarLegacyAgents.feature('+d.id+',\''+e(f.key)+'\','+(f.enabled?'false':'true')+')">'+(f.enabled?'ON':'OFF')+'</button></div>'}).join('');const periods=['today','week','month'].map(function(p,k){const x=d.periods&&d.periods[p]||{};return '<button class="v2-card" style="text-align:left;color:var(--tx)" onclick="RahbarLegacyAgents.periodById('+d.id+',\''+p+'\')"><small>'+['BUGUN','7 KUN','30 KUN'][k]+'</small><b>'+money(x.deliveredUsd)+' $</b><small>'+Number(x.visits||0)+' tashrif · '+Number(x.newClients||0)+' yangi</small></button>'}).join('');sheet('Agent · '+d.name,'<div class="v2-grid three"><div class="v2-card"><small>Mijozlar</small><b>'+d.clients+'</b></div><div class="v2-card"><small>Naqd USD</small><b>'+money(d.cashUsd)+'</b></div><div class="v2-card"><small>Pending</small><b>'+money(d.pendingHandoverUsd)+'</b></div></div><div class="v2-note">'+e(d.shiftOpen?'Smena ochiq':'Smena yopiq')+' · '+e(d.lastGpsTs?'GPS '+when(d.lastGpsTs):'GPS yo‘q')+'</div><div class="v2-grid three">'+periods+'</div><h3 style="font-size:13px;margin:15px 0 6px">Agentdagi tovar</h3><div class="v2-list">'+(stock.length?stock.map(function(x){return '<div class="v2-item"><b>'+e(x.name)+'</b><small>'+x.qty+' dona</small></div>'}).join(''):'<div class="v2-item"><small>Tovar qoldig‘i yo‘q</small></div>')+'</div><h3 style="font-size:13px;margin:15px 0 6px">Huquqlar</h3>'+feats+'<div class="v2-actions three"><button class="v2-btn" onclick="RahbarLegacyAgents.rename('+d.id+')">✏️ Nom</button><button class="v2-btn" onclick="RahbarLegacyAgents.route('+d.id+')">🧭 Marshrut</button><button class="v2-btn" onclick="RahbarLegacyAgents.transfer('+d.id+')">🔁 ID</button>'+(d.primaryAdmin?'<button class="v2-btn danger" onclick="RahbarLegacyAgents.deactivate('+d.id+')">⛔ Bloklash</button>':'')+'<button class="v2-btn primary" onclick="RahbarLegacyAgents.manage()">⚙️ Barchasi</button></div>')}
async function profileById(id){const i=as().findIndex(function(a){return Number(a.id)===Number(id)});if(i>=0)return profile(i);try{const d=await api('agent_detail',{agentId:id});renderProfile(d)}catch(x){toast(x.message||'Agent topilmadi')}}
async function manage(){sheet('Agentlar boshqaruvi','<div style="padding:20px;text-align:center;color:var(--mu)">Agentlar yuklanmoqda…</div>');try{const d=await api('agent_management');sheet('Agentlar boshqaruvi','<button class="v2-btn primary" style="width:100%;margin-bottom:10px" onclick="RahbarLegacyAgents.add()">＋ Yangi agent qo‘shish</button><div class="v2-list">'+(d.agents||[]).map(function(a){return '<div class="v2-row" onclick="RahbarLegacyAgents.profileById('+a.id+')" style="cursor:pointer"><div class="av">'+e((a.name||'?')[0])+'</div><div class="grow"><b>'+e(a.name)+'</b><small>ID '+a.id+' · '+a.clients+' mijoz · '+(a.shiftOpen?'Smena ochiq':a.active?'Smena yopiq':'Bloklangan')+'</small></div><span class="v2-badge">'+(a.active?'FAOL':'BLOK')+'</span></div>'}).join('')+'</div>'+note('Bloklash ma’lumotlarni o‘chirmaydi. Akkaunt almashtirish mijozlar, tovar, pul va tarixni yangi Telegram IDga ko‘chiradi.'))}catch(x){sheet('Agentlar boshqaruvi',note(x.message||'Agentlar yuklanmadi'))}}
function add(){sheet('Yangi agent','<div class="v2-form"><label>Telegram ID<input id="v2-aid" inputmode="numeric" placeholder="123456789"></label><label>Agent ismi<input id="v2-aname" placeholder="Agent ismi"></label>'+note('Yangi agent qo‘shilgandan keyin botga /start yuboradi.')+'<button class="v2-btn primary" onclick="RahbarLegacyAgents.previewAdd()">Tekshirish</button></div>')}
async function previewAdd(){try{const p=await api('agent_add_preview',{id:document.getElementById('v2-aid').value,name:document.getElementById('v2-aname').value});confirmAction('Agent qo‘shish','Yangi agent: <b>'+e(p.name)+'</b><br>ID: <b>'+p.id+'</b>','agent_add_commit',{id:p.id,name:p.name})}catch(x){toast(x.message||'Tekshirib bo‘lmadi')}}
function rename(id){const a=aById(id);sheet('Agent nomini o‘zgartirish','<div class="v2-form"><label>Yangi ism<input id="v2-arename" value="'+e(a?a.name:'')+'"></label><button class="v2-btn primary" onclick="RahbarLegacyAgents.previewRename('+id+')">Tekshirish</button></div>')}
async function previewRename(id){try{const p=await api('agent_rename_preview',{agentId:id,name:document.getElementById('v2-arename').value});confirmAction('Nomni o‘zgartirish','Eski: <b>'+e(p.oldName)+'</b><br>Yangi: <b>'+e(p.newName)+'</b>','agent_rename_commit',{agentId:id,name:p.newName})}catch(x){toast(x.message||'Tekshirib bo‘lmadi')}}
function transfer(id){sheet('Agent akkauntini almashtirish','<div class="v2-form"><label>Yangi Telegram ID<input id="v2-atrans" inputmode="numeric"></label>'+note('Eski ID bloklanadi. Mijoz, tovar, pul va tarix yangi IDga o‘tadi. Smena yopiq bo‘lishi kerak.')+'<button class="v2-btn primary" onclick="RahbarLegacyAgents.previewTransfer('+id+')">Tekshirish</button></div>')}
async function previewTransfer(id){try{const p=await api('agent_transfer_preview',{agentId:id,newId:document.getElementById('v2-atrans').value});confirmAction('Akkaunt almashtirish','Agent: <b>'+e(p.agent)+'</b><br>Yangi ID: <b>'+p.newId+'</b><br>Mijozlar: '+p.clients+'<br>Pul: '+money(p.cashUsd)+' USD','agent_transfer_commit',{agentId:id,newId:p.newId})}catch(x){toast(x.message||'Tekshirib bo‘lmadi')}}
async function deactivate(id){try{const p=await api('agent_deactivate_preview',{agentId:id});confirmAction('Agentni bloklash','<b>'+e(p.agent)+'</b><br>'+e(p.warning)+'<br>Mijozlar: '+p.clients+' · Pul: '+money(p.cashUsd)+' USD','agent_deactivate_commit',{agentId:id})}catch(x){toast(x.message||'Bloklab bo‘lmadi')}}
function confirmAction(title,msg,action,payload){pending={action:action,payload:payload};sheet(title,'<div class="v2-note">'+msg+'</div><div class="v2-actions"><button class="v2-btn primary" onclick="RahbarLegacyAgents.commit()">✅ Tasdiqlash</button><button class="v2-btn" onclick="closeS()">Bekor qilish</button></div>')}
async function commit(){if(!pending)return;const p=pending;pending=null;try{const r=await api(p.action,Object.assign({},p.payload,{confirm:true}));await V.reload();toast('✅ O‘zgarish saqlandi');if(r.agent&&r.agent.id)profileById(r.agent.id);else manage()}catch(x){toast(x.message||'Saqlanmadi')}}
async function feature(id,key,enabled){if(!confirm((enabled?'Yoqish':'O‘chirish')+': '+key+' ?'))return;try{const r=await api('agent_feature_set',{agentId:id,feature:key,enabled:!!enabled,confirm:true});toast('Huquq yangilandi');await V.reload();renderProfile(r.agent)}catch(x){toast(x.message||'Huquq saqlanmadi')}}
async function route(id){try{go(1);await new Promise(function(r){setTimeout(r,180)});await V.renderAgentMap();const d=await api('route',{agentId:id});if(!d.points||!d.points.length){toast('Oxirgi smenada GPS nuqta yo‘q');return}await V.loadLeaflet();if(typeof ymapObj==='undefined'||!ymapObj){toast('Xarita hali tayyor emas');return}if(window.__v2RouteLayer){try{ymapObj.removeLayer(window.__v2RouteLayer)}catch(_){}}window.__v2RouteLayer=L.polyline(d.points.map(function(p){return [p.lat,p.lon]}),{color:'#2367f5',weight:4,opacity:.9}).addTo(ymapObj);ymapObj.fitBounds(window.__v2RouteLayer.getBounds().pad(.15),{maxZoom:15,animate:false});toast('Marshrut · '+d.points.length+' GPS nuqta')}catch(x){toast(x.message||'Marshrut ochilmadi')}}
async function period(i,p){const a=aAt(i);if(a)periodById(a.id,p)}
async function periodById(id,p){const labels={today:'Bugun',week:'7 kun',month:'30 kun'};if(!labels[p])return;sheet(labels[p]+' · Natijalar','<div style="padding:20px;text-align:center;color:var(--mu)">Marshrut va tashriflar yuklanmoqda…</div>');try{const d=await api('agent_period_detail',{agentId:id,period:p}),gps=d.route||{},news=d.newClients||[],vis=d.visits||[];sheet(d.label+' · '+d.agent,'<div class="v2-grid three"><div class="v2-card"><small>Yangi mijoz</small><b>'+d.newClientsTotal+'</b></div><div class="v2-card"><small>Tashrif</small><b>'+d.visitsTotal+'</b></div><div class="v2-card"><small>GPS nuqta</small><b>'+gps.gpsTotal+'</b></div></div><div id="v2-period-map"></div>'+note(gps.sampled?'Ko‘p GPS nuqtasi tezlik uchun tanlab ko‘rsatildi.':'Ko‘k chiziq — saqlangan GPS marshruti. Mijoz markerlari saqlangan koordinata.')+'<h3 style="font-size:13px">Yangi mijozlar</h3><div class="v2-list">'+(news.length?news.slice(0,30).map(function(c){return '<div class="v2-item"><b>'+e(c.name)+'</b><small>'+e(c.address||'')+' · '+when(c.ts)+'</small></div>'}).join(''):'<div class="v2-item"><small>Yangi mijoz yo‘q</small></div>')+'</div><h3 style="font-size:13px">Tashriflar</h3><div class="v2-list">'+(vis.length?vis.slice(0,30).map(function(v){return '<div class="v2-item"><b>'+e(v.name)+'</b><small>'+e(v.status||'Tashrif')+' · '+when(v.ts)+(v.note?' · '+e(v.note):'')+'</small></div>'}).join(''):'<div class="v2-item"><small>Tashrif yo‘q</small></div>')+'</div>');drawPeriod(d)}catch(x){sheet(labels[p]+' · Natijalar',note(x.message||'Ma’lumot yuklanmadi'))}}
async function drawPeriod(d){try{const LL=await V.loadLeaflet(),el=document.getElementById('v2-period-map');if(!el)return;if(periodMap){try{periodMap.remove()}catch(_){}periodMap=null}periodMap=LL.map('v2-period-map',{zoomControl:true,attributionControl:true,preferCanvas:true}).setView([40.55,70.94],9);LL.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:17,updateWhenIdle:true,keepBuffer:1}).addTo(periodMap);periodLayer=LL.layerGroup().addTo(periodMap);const bounds=[];(d.route&&d.route.segments||[]).forEach(function(seg){const pts=seg.filter(function(p){return Number.isFinite(Number(p.lat))&&Number.isFinite(Number(p.lon))}).map(function(p){return [Number(p.lat),Number(p.lon)]});if(pts.length>1)LL.polyline(pts,{color:'#2367f5',weight:4,opacity:.9}).addTo(periodLayer);pts.forEach(function(p){bounds.push(p)})});const seen=new Map();(d.newClients||[]).forEach(function(c){seen.set(c.id,Object.assign({},c,{isNew:true,visits:0}))});(d.visits||[]).forEach(function(v){const z=seen.get(v.clientId)||Object.assign({},v,{id:v.clientId,isNew:false,visits:0});z.visits++;seen.set(v.clientId,z)});seen.forEach(function(c){if(!Number.isFinite(Number(c.lat))||!Number.isFinite(Number(c.lon)))return;const both=c.isNew&&c.visits,color=both?'#8b5cf6':c.isNew?'#16b364':'#f59e0b',glyph=both?'★':c.isNew?'＋':'✓',icon=LL.divIcon({className:'',html:'<div class="ymap-dot" style="width:26px;height:26px;display:grid;place-items:center;color:white;background:'+color+'">'+glyph+'</div>',iconSize:[26,26],iconAnchor:[13,13]});LL.marker([Number(c.lat),Number(c.lon)],{icon:icon}).addTo(periodLayer).bindPopup('<b>'+e(c.name||'Mijoz')+'</b><br><small>'+e(c.address||'')+'</small>');bounds.push([Number(c.lat),Number(c.lon)])});if(bounds.length)periodMap.fitBounds(LL.latLngBounds(bounds).pad(.15),{maxZoom:14,animate:false});setTimeout(function(){if(periodMap)periodMap.invalidateSize(false)},180)}catch(x){const el=document.getElementById('v2-period-map');if(el)el.innerHTML='<div style="padding:20px;color:var(--mu)">Xarita ochilmadi: '+e(x.message||'xato')+'</div>'}}
window.RahbarLegacyAgents={profile:profile,profileById:profileById,manage:manage,add:add,previewAdd:previewAdd,rename:rename,previewRename:previewRename,transfer:transfer,previewTransfer:previewTransfer,deactivate:deactivate,commit:commit,feature:feature,route:route,period:period,periodById:periodById};
enhance();setTimeout(enhance,700);window.addEventListener('rahbar-v2-data',function(){enhance()});
})();